version: 2

models:
  - name: time_spine
    time_spine:
      standard_granularity_column: date_day
    columns:
      - name: date_day
        granularity: day

  - name: daily_order_metrics
    config:
      materialized: view

  - name: live_orders_latest
    config:
      materialized: view